<?php
if(!defined('_MALLSET_')) exit;

$admin_minishop = false;
$admin_seller = false;

if(in_array($code, array(
	'seller_main',
	'seller_info',
	'seller_baesong',
	'seller_goods_list',
	'seller_goods_form',
	'seller_goods_stock',
	'seller_goods_optstock',
	'seller_goods_xls_reg',
	'seller_goods_xls_reg_update',
	'seller_goods_xls_mod',
	'seller_goods_xls_mod_update',
	'seller_goods_xls_option_reg',
	'seller_goods_xls_option_reg_update',
	'seller_goods_brand_list',
	'seller_goods_brand_form',
	'seller_goods_qa',
	'seller_goods_qa_form',
	'seller_goods_review',
	'seller_odr_2',
	'seller_odr_3',
	'seller_odr_4',
	'seller_odr_5',
    'seller_order_delivery',
	'seller_odr_6',
	'seller_odr_7',
	'seller_odr_8',
	'seller_odr_9',
	'seller_odr_list',
	'seller_odr_stats',
	'seller_odr_balance',
	'seller_odr_delivery',
	'seller_odr_delivery_update',
	'seller_odr_account'))) {
	$admin_snb_file = 'admin_snb1.php';
	$admin_seller = true;
} else if(in_array($boardid, array('20','21'))) {
	$admin_snb_file = 'admin_snb1.php';
	$admin_seller = true;
} else if(in_array($code, array(
	'minishop_info',
	'minishop_term',
	'minishop_meta',
	'minishop_sns',
	'minishop_agree',
	'minishop_baesong',
	'minishop_keyword_list',
    'minishop_payhistory',
    'minishop_paylist',
	'minishop_sppointhistory',
	'minishop_sppointlist',
	'minishop_pg',
	'minishop_kakaopay',
	'minishop_naverpay',
	'minishop_logo',
	'minishop_banner_list',
	'minishop_banner_form',
	'minishop_mbanner_list',
	'minishop_mbanner_form',
	'minishop_best_item',
	'minishop_popup_list',
	'minishop_popup_form',
	'minishop_member_list',
	'minishop_register_form',
	'minishop_tree',
    'minishop_orgchart',
	'minishop_stats_day',
	'minishop_stats_month',
	'minishop_visit',
	'minishop_goods_admlist',
	'minishop_order_admlist',
	'minishop_goods_type',
	'minishop_category_list',
	'minishop_category_view',
	'minishop_goods_brand_list',
	'minishop_goods_brand_form',
	'minishop_goods_form',
	'minishop_goods_list',
	'minishop_goods_stock',
	'minishop_goods_optstock',
	'minishop_goods_review',
	'minishop_goods_xls_reg',
	'minishop_goods_xls_reg_update',
	'minishop_goods_xls_mod',
	'minishop_goods_xls_mod_update',
	'minishop_goods_xls_option_reg',
	'minishop_goods_xls_option_reg_update',
	'minishop_goods_qa',
	'minishop_goods_qa_form',
	'minishop_odr_1',
	'minishop_odr_2',
	'minishop_odr_3',
	'minishop_odr_4',
	'minishop_odr_5',
	'minishop_odr_6',
	'minishop_odr_7',
	'minishop_odr_8',
	'minishop_odr_9',
	'minishop_odr_list',
	'wzb_booking_list',
	'wzb_booking_status',
	'wzb_room_list',
	'wzb_room_form',
	'wzb_room_status',
	'wzb_price_list',
	'wzb_room_option_list',
	'wzb_room_option_form',
	'wzb_holiday_list',
	'wzb_pay_list',
	'wzb_config'
	))) {
	$admin_snb_file = 'admin_snb2.php';
	$admin_minishop = true;
} else if(in_array($boardid, array('22','36','50','51'))) {
	$admin_snb_file = 'admin_snb2.php';
	$admin_minishop = true;
}
?>